---
title: "Week 4 Assignment"
date: "May 14th 2019"
output: ioslides_presentation
runtime: shiny
---

## Introduction

- Sea temperatures from North West Mediterranean zone are analyzed in this exercise.

- Temperatures are measured in different depths: 0, -20, -50 and -80 meters.

- There is a mesure per each month since 2000 until 2017.

- Source data used is placed in: https://www.idescat.cat/pub/?id=aec&n=218&lang=es


## Monthly temperatures

```{r, echo=FALSE, warning=FALSE, message=FALSE}

library(dplyr)
library(tidyr)
library(plotly)

inidata <- read.table(file = "SeaTemps.txt", header=TRUE,sep=",")

pageWithSidebar(
    headerPanel("Select year"),
    sidebarPanel(sliderInput("iYear", 'Year',value = 2017, min = 2000, max = 2017, sep="")),
    mainPanel(plotlyOutput('plot1'))
)

output$plot1 <- renderPlotly({
            workdata <- inidata %>%
                filter(Year==input$iYear) %>%
                select(-Year) %>%
                gather(Depth,Temperature,-Month) %>%
                mutate(Month=factor(Month, levels = month.name))
            plot_ly(workdata,x=~Month,y=~Temperature,color=~Depth,type = "bar")
})
```


## Temperatures variation in depth

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)

inidata <- read.table(file = "SeaTemps.txt", header=TRUE,sep=",")

pageWithSidebar(
    headerPanel("Select year"),
    sidebarPanel(sliderInput("iYear", 'Year',value = 2017, min = 2000, max = 2017, sep="")),
    mainPanel(plotOutput('plot2'))
)

output$plot2 <- renderPlot({
            workdata <- inidata %>%
                filter(Year==input$iYear) %>%
                select(-Year) %>%
                gather(Depth,Temperature,-Month)
            ggplot(workdata,aes(x=Depth,y=Temperature,group=1))+ geom_line()+ facet_wrap(.~ Month, ncol = 4)+ scale_x_discrete(labels= c("0", "-20", "-50", "-80"))
})
```

## Get your prediction


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)

inidata <- read.table(file = "SeaTemps.txt", header=TRUE,sep=",")

pageWithSidebar(
    headerPanel(""),
    sidebarPanel(
        radioButtons("iDepth", "Select depth expressed in meters",
                     choices = c("0" = 3, "-20"=4, "-50"=5, "-80"=6), selected = 3),
        selectInput("iMonth", "Select month", 
                    choices = list("January","Febrary","March","April", "May", "June",
                                   "July", "August",
                                   "September", "October","November","December"),
                    selected = "January", multiple = FALSE),
        sliderInput("iYear", 'Select year', value = 2018, min = 2018, max = 2040, sep="")
    ),
    mainPanel(
        plotOutput('plot3')
    )
)

output$plot3 <- renderPlot({
            temp <- inidata[inidata$Month==input$iMonth,]
            workdata <- data.frame(Year=temp$Year, Temperature=temp[,as.numeric(input$iDepth)])
            modelFit <- lm(Temperature~Year, data=workdata)
            predictedTemps <- round(predict(modelFit, newdata=data.frame(Year=2000:2040)),1)
            predictedData <- data.frame(Year=2000:2040, Temperature=predictedTemps)
            pr <- as.character(predictedData[predictedData$Year==input$iYear,2])
            prmessage <- paste0("Temperature predicted: ", pr, "C")
            ggplot(workdata, aes(Year, Temperature)) + geom_point(color="blue") + 
                geom_smooth(data=predictedData,aes(x=Year, y=Temperature), method = "lm",se=FALSE,color="red")+geom_vline(aes(xintercept=2017)) +geom_point(aes(x=input$iYear,y=predictedData[predictedData$Year==input$iYear,2]),color="red",lwd=5)+geom_text(x=2030,y=13,label=prmessage)+ylim(10,25)
})
```


